### ISSUE TITLE
使用企业邮箱的情况

### ISSUE THREAD

**Issue by wangooooooo** [ZYunH/zmail#16]
邮件发送场景中，可能出现企业邮箱，如腾讯邮箱、网易企业邮箱。

**Comment by ZYunH** [comment]
这个场景考虑过了，功能已经添加，但是没有写进文档，这个功能暂时是自定义的，因为每个具体域名后面可能转接企业邮箱，后面会解决这个问题，现在具体的做法是自定义 server = zmail.server('userid','password',.smtp_address = 'xxxxxx',pop_address='xxxxx')，其他没有填写的会自动寻找 在腾讯企业邮箱测试过 没有发现问题

**Comment by wangooooooo** [comment]
谢谢解答~
