### ISSUE TITLE
improve:是否可以直接加入base64的解码

### ISSUE THREAD

**Issue by epirus** [ZYunH/zmail#17]
```python
mail = server.get_latest()
print(mail['subject'])
print(''.join(mail['contents']))

```
直接加入base64的解码是不是会好一点

**Comment by ZYunH** [comment]
实际上在解析的时候已经自动寻找编码然后尝试解码了，contents里面包含的是由boundary分开的原生信件（bytes），是用来给用户自定义解析的，可以看到在subject等头文件中，已经bytes被成功解码了
