### ISSUE TITLE
能不能增加支持text/html邮件正文啊

### ISSUE THREAD

**Issue by trackies01** [ZYunH/zmail#19]
小白一个，研究了好久也不知道该怎么让他显示text/html格式的邮件正文，我用了几个邮箱测试的邮件正文都是text/html的格式啊，或者有什么方法转码raw吗？

**Comment by ZYunH** [comment]
默认的Text格式的正文放在邮件的content字段里面，html格式的正文因为无法在文本情况下正确显示，只能依靠boundary来划分raw，而后再提取相应内容。
在0.1.0的第一个发行版中会优化content内容（其他issues加入的enhancement，目前在一些复合邮件中无法被正确提取），这个发行版将会在近期更新

**Comment by trackies01** [comment]
好的，辛苦了
