### ISSUE TITLE
时间筛选无效

### ISSUE THREAD

**Issue by createnewli** [ZYunH/zmail#27]
![image](https://user-images.githubusercontent.com/20616294/41197594-c25c0bca-6c96-11e8-891f-0d6f9446cb8f.png)
时间筛选看上去并没有效果，另外“date"输出的也是'10 Jun 2018 07:00:52 +0800'，而不是 年 月 日 时间 时区的格式

**Comment by ZYunH** [comment]
0.1.4版本解决了这个问题，这个问题来源是邮件时间有两种匹配模式，可能是旧协议的规定，现在已经做了兼容，可以更新一下试试，欢迎继续反馈~
