### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by GavinDingCoolapk** [ZYunH/zmail#30]
========== RESTART: C:\Users\Administrator\Desktop\mail\recieve.py ==========
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\mail\recieve.py", line 29, in <module>
    mail = server.get_latest()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\zmail\server.py", line 102, in get_latest
    server = self._init_pop3()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\zmail\server.py", line 159, in _init_pop3
    server = POP3Server(host, port, self.user, self.password, ssl)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\zmail\server.py", line 238, in __init__
    self.login()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\zmail\server.py", line 254, in login
    self.pop3.pass_(self.password)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\poplib.py", line 213, in pass_
    return self._shortcmd('PASS %s' % pswd)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\poplib.py", line 176, in _shortcmd
    return self._getresp()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\poplib.py", line 152, in _getresp
    raise error_proto(resp)
poplib.error_proto: b'-ERR \xb5\xc7\xc2\xbc\xcc\xab\xc6\xb5\xb7\xb1!\xc7\xeb\xbc\xec\xb2\xe9\xc4\xfa\xb5\xc4outlook, foxmail\xbb\xf2\xd5\xdf\xc6\xe4\xcb\xfc\xd7\xd4\xb6\xaf\xbc\xec\xb2\xe2\xd3\xca\xcf\xe4\xb5\xc4\xb9\xa4\xbe\xdf(\xc0\xfd\xc8\xe7\xcd\xf8\xd2\xd7popo\xb5\xc8\xc1\xc4\xcc\xec\xb9\xa4\xbe\xdf),\xbd\xab\xbc\xec\xb2\xe2\xb5\xc4\xca\xb1\xbc\xe4\xbc\xe4\xb8\xf4\xb5\xf7\xb4\xf3\xd2\xbb\xd0\xa9\xa3\xac\xc0\xfd\xc8\xe75\xb7\xd6\xd6\xd3\xbc\xe0\xb2\xe2\xd2\xbb\xb4\xce.'

本来还可以用的，后来不知道为啥就这样了

**Comment by ZYunH** [comment]
现在这个问题还能重现吗？

**Comment by sanqiaiziji** [comment]
> 现在这个问题还能重现吗？

我得到了相同的问题，我在前几次使用中一直没有报错，但是在大量循环使用后，出现这个错误，且清空工作区后重启代吗，也无法避免这个错误

**Comment by GavinDingCoolapk** [comment]
> 现在这个问题还能重现吗？
已经解决。
登陆次数过于频繁所导致。（循环登陆间隔要大于5分钟）

**Comment by GavinDingCoolapk** [comment]
> 现在这个问题还能重现吗？
> 
> 我得到了相同的问题，我在前几次使用中一直没有报错，但是在大量循环使用后，出现这个错误，且清空工作区后重启代吗，也无法避免这个错误

已经解决。
登陆次数过于频繁所导致。（循环登陆间隔要大于5分钟）

**Comment by sanqiaiziji** [comment]
非常感谢你的回信，此问题是由于频繁登录导致的问题，我在设置sleep=5min的时候，过了一段时间仍就报错。我已经将sleep设置为10min，暂时没有再出现此问题。
另外我想知道，我改如何获取此邮件是已读或未读？
期待你的回复。

发送自 Windows 10 版邮件应用

发件人: GavinDingCoolapk
发送时间: 2019年6月1日 19:52
收件人: ZYunH/zmail
抄送: BUPT-wxq; Comment
主题: Re: [ZYunH/zmail] 登录失败 (#30)


现在这个问题还能重现吗？
已经解决。
登陆次数过于频繁所导致。（循环登陆间隔要大于5分钟）

**Comment by GavinDingCoolapk** [comment]
> 非常感谢你的回信，此问题是由于频繁登录导致的问题，我在设置sleep=5min的时候，过了一段时间仍就报错。我已经将sleep设置为10min，暂时没有再出现此问题。
> 另外我想知道，我改如何获取此邮件是已读或未读？
> 期待你的回复。
> 
> 发送自 Windows 10 版邮件应用
> 
> 发件人: GavinDingCoolapk
> 发送时间: 2019年6月1日 19:52
> 收件人: ZYunH/zmail
> 抄送: BUPT-wxq; Comment
> 主题: Re: [ZYunH/zmail] 登录失败 (#30)
> 
> 
> 现在这个问题还能重现吗？
> 已经解决。
> 登陆次数过于频繁所导致。（循环登陆间隔要大于5分钟）
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

我不很清楚是否支持这一功能。
但可以通过获取邮件的接受时间来实现。

我的想法：
1、获取邮件接收时间（date = mail['date']）。
2、记录这个时间。
3、当再一次读取邮件时，若检测到其接收时间已经被记录，则这封邮件是已读的。
<img width="438" alt="捕获" src="https://user-images.githubusercontent.com/40265541/58755452-13890680-8517-11e9-9b3a-73e9f9d352bd.PNG">

**Comment by GavinDingCoolapk** [comment]
> 非常感谢你的回信，此问题是由于频繁登录导致的问题，我在设置sleep=5min的时候，过了一段时间仍就报错。我已经将sleep设置为10min，暂时没有再出现此问题。
> 另外我想知道，我改如何获取此邮件是已读或未读？
> 期待你的回复。
> 
> 发送自 Windows 10 版邮件应用
> 
> 发件人: GavinDingCoolapk
> 发送时间: 2019年6月1日 19:52
> 收件人: ZYunH/zmail
> 抄送: BUPT-wxq; Comment
> 主题: Re: [ZYunH/zmail] 登录失败 (#30)
> 
> 
> 现在这个问题还能重现吗？
> 已经解决。
> 登陆次数过于频繁所导致。（循环登陆间隔要大于5分钟）
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

如果我理解上有偏差请告诉我。

**Comment by GavinDingCoolapk** [comment]
> 非常感谢你的回信，此问题是由于频繁登录导致的问题，我在设置sleep=5min的时候，过了一段时间仍就报错。我已经将sleep设置为10min，暂时没有再出现此问题。
> 另外我想知道，我改如何获取此邮件是已读或未读？
> 期待你的回复。
> 
> 发送自 Windows 10 版邮件应用
> 
> 发件人: GavinDingCoolapk
> 发送时间: 2019年6月1日 19:52
> 收件人: ZYunH/zmail
> 抄送: BUPT-wxq; Comment
> 主题: Re: [ZYunH/zmail] 登录失败 (#30)
> 
> 
> 现在这个问题还能重现吗？
> 已经解决。
> 登陆次数过于频繁所导致。（循环登陆间隔要大于5分钟）
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

此法不适用于手动查看的邮件

**Comment by sanqiaiziji** [comment]
> > 现在这个问题还能重现吗？
> > 已经解决。
> > 登陆次数过于频繁所导致。（循环登陆间隔要大于5分钟）

我在将sleep设置为10分钟，在运行十五个小时之后，突然显示频繁登录，之后便无法继续访问邮箱
