### ISSUE TITLE
不能发送电子书格式的附件，附件的文件名不能为中文，否则会出错

### ISSUE THREAD

**Issue by mskyer** [ZYunH/zmail#37]
你好，我打算用zmail来给自己推送电子书，但是发现了几个问题：
1、不能发送电子书格式的附件（如mobi格式的）
2、发送的附件名称不能为中文
3、推送的txt格式的电子书，亚马逊收不到

**Comment by ZYunH** [comment]
#38 这是由中文编码引起的错误 已经修复了 可以重新尝试一下 0.1.8版本

**Comment by mskyer** [comment]
好了，已经可以正常使用了，谢谢你
