### ISSUE TITLE
腾讯企业邮箱extmail不支持，希望能够支持腾讯企业邮箱

### ISSUE THREAD

**Issue by swissfiscal** [ZYunH/zmail#39]
希望能够支持腾讯企业邮箱extmail

**Comment by ZYunH** [comment]
已经有了支持 只是没写入文档 只需要设定zmai.server('user','password',config='qq')即可 文档更新的时候会加入

**Comment by swissfiscal** [comment]
试了。果然可以用，谢谢。请更新到文档中吧
