### ISSUE TITLE
华润集团电子邮件系统 - Coremail好像不支持

### ISSUE THREAD

**Issue by crctrust** [ZYunH/zmail#41]
华润集团电子邮件系统 - Coremail好像不支持，最近发现这个神奇，非常厉害。

**Comment by crctrust** [comment]
@crctrust.com；smtp_server = 'crmail.crc.com.cn'

**Comment by ZYunH** [comment]
对于企业特定的邮箱（而非腾讯企业邮箱这样的大型服务商）建议使用自定义配置，具体例子如server = zmail.server('username','password',smtp_host='smtp.163.com',smtp_port=994,smtp_ssl=True,pop_host='pop.163.com',pop_port=995,pop_tls=True)   而大型的服务商已经提供支持 具体请查看readme
