### ISSUE TITLE
使用html作为报错，麻烦解决一下

### ISSUE THREAD

**Issue by crctrust** [ZYunH/zmail#42]
File "C:\ProgramData\Anaconda3\lib\site-packages\zmail\server.py", line 67, in send_mail
    server.send(recipients, mail, timeout, self.auto_add_to, tls)

  File "C:\ProgramData\Anaconda3\lib\site-packages\zmail\server.py", line 221, in send
    server.sendmail(self.user, recipient, message.as_string())

  File "C:\ProgramData\Anaconda3\lib\site-packages\zmail\message.py", line 140, in as_string
    self.pre_send()

  File "C:\ProgramData\Anaconda3\lib\site-packages\zmail\message.py", line 122, in pre_send
    _combine_message += i

TypeError: must be str, not NoneType

使用html作为报错，麻烦解决一下

**Comment by crctrust** [comment]
感谢及时反馈，Python为3.6.1版本，zmail应该为为0.1.8版本。



华润信托-陈良方
 
发件人： ZYunH
发送时间： 2018-08-21 20:19
收件人： ZYunH/zmail
抄送： crctrust; Author
主题： Re: [ZYunH/zmail] 使用html作为报错，麻烦解决一下 (#42)
麻烦提供以下信息： 1.zmail的版本号 2.python版本号 3.操作平台
（如果发现问题，请先行更新zmail，可解决大部分问题）

**Comment by ZYunH** [comment]
尝试了一些方法也无法复现这个问题 麻烦先将zmail升级到最先版本 如果依然出现这个问题 方便的话提供一下html文件的形式或者结构

**Comment by ZYunH** [comment]
@solomsk 大概率是看代码的时候不小心修改了源代码 请重新安装 如果还能复现请反馈

**Comment by crctrust** [comment]
你好，现在zmail仅支持收件人仅能看到自己，不能看到其他的收件人，请问这个能否调整，默认收件人可以看到所有的收件人。



华润信托-陈良方
 
发件人： ZYunH
发送时间： 2018-08-29 20:33
收件人： ZYunH/zmail
抄送： crctrust; Author
主题： Re: [ZYunH/zmail] 使用html作为报错，麻烦解决一下 (#42)
@solomsk 大概率是看代码的时候不小心修改了源代码 请重新安装 如果还能复现请反馈

**Comment by ZYunH** [comment]
#36
