### ISSUE TITLE
Mail-in-a-Box自建邮局SMTP链接不上

### ISSUE THREAD

**Issue by liangnicho** [ZYunH/zmail#48]
SMTP和POP等信息如下，想使用zmail发送邮件

server=zmail.server('1231231@xxx.com', 'pass', smtp_host='mail.xxx.com', smtp_port=587,smtp_tls=Ture,pop_host='mail.xxx.com',pop_port=995,pop_ssl=True)

pop没问题，但SMTP一直提示出错，smtp_tls=Ture和smtp_ssl=Ture都提示同样的报错，请问如何如何设置？
报错ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1045)
<table class="table">
					<thead>
						<tr><th>Option</th> <th>Value</th></tr>
					</thead>
					<tbody><tr><th>Protocol/Method</th> <td>IMAP</td></tr>
					<tr><th>Mail server</th> <td>mail.xxxxx.com</td>
					</tr><tr><th>IMAP Port</th> <td>993</td></tr>
					<tr><th>IMAP Security</th> <td>SSL or TLS</td></tr>
					<tr><th>SMTP Port</th> <td>587</td></tr>
					<tr><th>SMTP Security </th><td>STARTTLS <small>(“always” or “required”, if prompted)</small></td></tr>
					<tr><th>Username:</th> <td>Your whole email address.</td></tr>
					<tr><th>Password:</th> <td>Your mail password.</td></tr>
					</tbody></table>

**Comment by ZYunH** [comment]
在自定义设置时 不可同时将smtp_tls 和 smtp_ssl 同时设置为True 
如果还有问题请重新安装zmail 目前刚刚更新了新版本 修复了之前的很多问题
