### ISSUE TITLE
使用腾讯的foxmail邮箱发邮件没反应，没报错也没成功

### ISSUE THREAD

**Issue by Lannisterstarrydawn** [ZYunH/zmail#51]
使用腾讯的foxmail邮箱发邮件没反应，没报错也没成功

**Comment by ZYunH** [comment]
可以看一下是否存在于垃圾邮件中

**Comment by Wangjunyu** [comment]
遇到类似的情况，是阿里的公司邮箱。后来发现是因为在短时间内同样内容的邮件会被当成是同一封邮件的重试（基于幂等性校验？），既不退信，也没有报错，也收不到...

在测试邮件里增加随机码，标题上增加当时时间（精确到秒），可以解决。

**Comment by yiwanggecaonima** [comment]
那么如果增加若干随机,比如说一分钟内发几封邮件 相似度是60%,还会出现这种情况吗?我认为163还是很严的,要高度随机

**Comment by ZYunH** [comment]
有可能是服务器为了控制流量的优化 我在测试中(公用邮箱)并没有发现这个问题 同样内容短时间发送可以正常接收 后续可能在邮箱中增加一些随机值来抵消基于摘要算法的重复检测的影响

**Comment by ZYunH** [comment]
如果加入随机内容依然没有解决 并且排除邮箱服务器的问题 可以重新打开这个issue
