### ISSUE TITLE
对多人群发会被拒信吗？

### ISSUE THREAD

**Issue by Lannisterstarrydawn** [ZYunH/zmail#53]
每天定时发送几千封给不同的人会被拒信吗？

**Comment by ZYunH** [comment]
这取决于你的邮箱的服务器 zmail只负责将信息传递到服务器 而是否发送取决于你所在的邮箱服务器

**Comment by Lannisterstarrydawn** [comment]
比如用qq邮箱向上千个客户邮箱（可能是qq也可能是别的邮箱）发送信息，这些客户邮箱都将发信人的邮箱设为白名单，会被拒收吗？
