### ISSUE TITLE
几个小bug

### ISSUE THREAD

**Issue by kplam** [ZYunH/zmail#54]
1.格式化时间未修正时区；
2.对未标格式时间未作处理，直接报错；
3.大量收取邮件时比较容易超时；
4.base64解码时，如果原密文长度缺少=，会解密失败；
5.缺失编码识别机制，极少数邮件头中标注编码并不能解码，如windows-874，转码逻辑稍显简漏；
6.邮件头不含:行未作处理；

另建议增加 imap server以同步发件箱等其他信箱，Mail实例是否应该增加Cc的邮件头信息。

**Comment by ZYunH** [comment]
1.时区未加入 之前的测试发现了一些问题 会在后面版本更新
2.无法识别的时间会为None 报的是warning
3.这个考虑过加入cache，但是随之而来的会有缓存重建问题，还在考虑中，目前建议使用stat + get_mail
4.这个之前没遇到过 是否有样例提供
5.头文件的编码原本是用标准库的解析函数 但是标准库无法识别国内几个邮箱的header 所以自己封装了  这个并不是解析错误 而是python根本就不支持这个编码
6.没有:的行会被视为上一行的一部分，本不应该处理

其他：Cc在Headers里面有 只是没有在show中显示出来
