### ISSUE TITLE
smtplib.SMTPServerDisconnected: Server not connected

### ISSUE THREAD

**Issue by ecithy** [ZYunH/zmail#59]
放在本地可以，在服务器上执行报错

**Comment by ZYunH** [comment]
麻烦提供一下服务器的运行环境

**Comment by ecithy** [comment]
aws Ubuntu------------------ 原始邮件 ------------------
发件人: "ZYunH"<notifications@github.com>
发送时间: 2019年4月24日(星期三) 下午3:21
收件人: "ZYunH/zmail"<zmail@noreply.github.com>;
抄送: "ecithy"<598779784@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ZYunH/zmail] smtplib.SMTPServerDisconnected: Server notconnected (#59)



麻烦提供一下&#x670D;务器的运行环境
 
&mdash;

**Comment by ZYunH** [comment]
需要zmail版本 以及对应的py版本
