### ISSUE TITLE
添加中文别名问题

### ISSUE THREAD

**Issue by toptonyliu** [ZYunH/zmail#60]
在发送邮件是，FROM字段添加中文别名会出现解析错误，
如‘form’:'公告栏<put@pp.cn>',发件时会解析为"公告栏<put，阅读了相关源码，暂未找到解决方案，烦请指点迷津

**Comment by ZYunH** [comment]
更新下最新版本 现在使用元祖的方式解决 之前的from字段可能会出现一些问题

**Comment by toptonyliu** [comment]
update最新version后参考api中you can define sender's name by add 'from':'Boss <mymail@foo.com>' in your mail.
中文nickname依旧有问题，api调用的方式是否有变化？

**Comment by ZYunH** [comment]
测试了一下 使用类似于'from':'测试 <mymail@foo.com>' 的形式并没有问题 其次这个字段是放在邮件中的 也就是和subject为同一级 例如srv.send_mail(('收件人','foo@qq.com'),{'subject':'123','from':'发件人 <bar@126.com>'})
