### ISSUE TITLE
server.stat()获取到的邮件数目不对

### ISSUE THREAD

**Issue by steinvenic** [ZYunH/zmail#62]
总是少于服务器上的数量，使用QQ和Sina邮箱都有这个问题

**Comment by ZYunH** [comment]
目前我只在gmail发现了这个问题 debug过程显示客户端发送了正确的stat命令 但是服务器返回的数量并不正确 所以问题大概率出现在服务器上 也就是你需要到邮箱的pop设置里面控制其收取数量和范围

**Comment by steinvenic** [comment]
但是我用[IMAPClient](https://github.com/mjs/imapclient)就比较准，我邮件有4000封，zmail只能获取到不到300封，难道是POP协议的问题？

**Comment by ZYunH** [comment]
有可能 这俩是分开设置的 zmail正确发出了pop3的stat 但是接收到的数目在某些邮箱上确实有问题

**Comment by ZYunH** [comment]
目前看来 只有邮件数目达到300以上才可能出现 之前有个邮箱有数千邮件 但是并没有出现这个问题 我后续再排查一下

**Comment by steinvenic** [comment]
好滴，Thanks^_^

**Comment by steinvenic** [comment]
是POP服务器设置的问题。
看了下QQ邮箱，默认只接收30天内的，最多也就能设置成180天内，还是希望大神早点支持IMAP啊~

**Comment by steinvenic** [comment]
不好意思，看了下POP可以设置接收全部，QQ邮箱

**Comment by ZYunH** [comment]
看样子只能等后续更新版本迁移到imap才行 pop还是有些默认的设置问题
