### ISSUE TITLE
之前在测试正常的代码，突然报错

### ISSUE THREAD

**Issue by cclmyy** [ZYunH/zmail#64]
AttributeError: module 'zmail' has no attribute 'server'

之前测试是正常的，不知道为什么就报错了。

**Comment by cclmyy** [comment]
python 3.7.3   Anaconda   zmail版本  0.2.5

**Comment by cclmyy** [comment]
报错代码：server = zmail.server('xxxxx.com', 'password')

**Comment by ZYunH** [comment]
看看是不是命名了一个叫zmail的变量 或者本地的zmail包被修改了

**Comment by cclmyy** [comment]
> 看看是不是命名了一个叫zmail的变量 或者本地的zmail包被修改了

没有另外命名zmail的变量，完整代码：
# $language = "python"
# $interface = "1.0"
#coding=utf8

import zmail
server = zmail.server('yourmail@example.com', 'yourpassword')

然后换了一台电脑重新安装的 pip install zmail 运行这段代码，问题依旧。

**Comment by ZYunH** [comment]
你提供的代码可以正常使用，可以尝试用dir(zmail) 获取更多信息我来判断一下问题，此外 zmail只运行在py3的环境中

**Comment by cclmyy** [comment]
> 你提供的代码可以正常使用，可以尝试用dir(zmail) 获取更多信息我来判断一下问题，此外 zmail只运行在py3的环境中

python环境没问题，是3.7。 print(dir(zmail))结果是：
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'jieshou_mailya', 'send_mailya', 'zmail']Traceback (most recent call last):

**Comment by cclmyy** [comment]
> 你提供的代码可以正常使用，可以尝试用dir(zmail) 获取更多信息我来判断一下问题，此外 zmail只运行在py3的环境中

自己犯傻。找到问题了。有个文件用了zmail的名字~唉 脑子呀~感谢大佬的解答~
