### ISSUE TITLE
用163的smtp发邮件给qq邮箱，不成功

### ISSUE THREAD

**Issue by gitscamI** [ZYunH/zmail#67]
最后被退信了，说是垃圾邮件，什么原因啊？server中的参数有什么需要特别设置的吗？

**Comment by ZYunH** [comment]
原因有很多 例如发送重复内容以及一些邮件服务器的屏蔽词 或者 发送频率过高 一般来说如果server设置问题则每次发送都会失败

**Comment by gitscamI** [comment]
谢谢指点，确实是这个问题，能不能说一下内容应该注意什么才才能发送？？有些什么屏蔽词

**Comment by ZYunH** [comment]
一般会有多少分钟内不能超过多少封 屏蔽词各家都会有不同 一般都靠经验或者别人的总结
