### ISSUE TITLE
用server.send_mail发送邮件，发完后不报错，也没显示

### ISSUE THREAD

**Issue by gitscamI** [ZYunH/zmail#68]
用server.send_mail发送邮件，发完后不报错，也没显示，进收件箱也没有看到，用什么方法知道发送是否成功和失败，以及相关的其它状态？？谢谢

**Comment by ZYunH** [comment]
一般没报错就默认为成功 另外可以用返回值来观察 如果发送成功会返回True 希望可以帮到你 :)
