### ISSUE TITLE
AttributeError: module 'zmail' has no attribute 'server'

### ISSUE THREAD

**Issue by ksgujie** [ZYunH/zmail#71]
win10  python 3.7

import zmail
mail_content = {
    'subject': 'Success!',  # 随便填写
    'content_text': 'This message from zmail!',  # 随便填写
}
server = zmail.server('12345678@qq.com','000')
server.send_mail('555555@qq.com', mail_content)

--------------------------------------------------------
C:\Python\python.exe C:/Users/Eyes/Desktop/python/Summary/zmail.py
Traceback (most recent call last):
  File "C:/Users/Eyes/Desktop/python/Summary/zmail.py", line 1, in <module>
    import zmail
  File "C:\Users\Eyes\Desktop\python\Summary\zmail.py", line 9, in <module>
    server = zmail.server('12345678@qq.com','000')
AttributeError: module 'zmail' has no attribute 'server'

Process finished with exit code 1

**Comment by ksgujie** [comment]
官方示例代码都运行不起来

**Comment by ZYunH** [comment]
不要把一些文件命名为zmail.py 会与库的名字重复 只支持>=python3.5
