### ISSUE TITLE
使用get_mails一段时间后会出现BrokenPipeError: [Errno 32] Broken pipe错误

### ISSUE THREAD

**Issue by MyCodeBattle** [ZYunH/zmail#73]
一开始我以为是并发请求导致出错，后来把get_mails加了锁一段时间后还是会出现这个错误，请问是什么原因？

**Comment by ZYunH** [comment]
这个问题是尝试access一个closed的pipe导致的 get_mails的实现会创建一个新的conn 按理说不会出现  请问服务里面有什么其他复用的措施么?

**Comment by chnlcq** [comment]
我也遇到了这个同样得问题

**Comment by ZYunH** [comment]
建议可以贴一下报错的context 可以更好的定位问题

**Comment by ZYunH** [comment]
这个一段时间大概是多少呢 我预计问题出现在不同的邮箱服务器在不同的时间间隔后会主动断开连接

**Comment by ZYunH** [comment]
更新到最新的0.2.6版本可能可以解决这个问题

**Comment by MyCodeBattle** [comment]
> 更新到最新的0.2.6版本可能可以解决这个问题

我之后把这个异常catch了，然后重新连接邮件服务器，也就这么用下去了。昨天我更新了一下，重新连接的日志依然存在，虽然具体报错没看到但是我觉得可能还是这个问题。

**Comment by ZYunH** [comment]
这里面如果还有除了IOError的exception其实可以贴一下 目前没有测试到更具体的错误类型

**Comment by ZYunH** [comment]
目前给POP也加入了相应的措施 在0.2.7这个问题应该可以被解决
