### ISSUE TITLE
请问如何下载未读邮件

### ISSUE THREAD

**Issue by Albert822** [ZYunH/zmail#77]

**Comment by ZYunH** [comment]
未读和已读邮件都在同一位置并不做区分 直接下载即可 如要筛选 使用get_mails即可

**Comment by Albert822** [comment]
你说的筛选是按照什么筛选啊，不是按照已读或未读筛选吧

**Comment by ZYunH** [comment]
按照名字时间等筛选 未读已读在SMTP里面大部分邮箱并不显示支持
