### ISSUE TITLE
server.stat()不能得到正确的邮件数目

### ISSUE THREAD

**Issue by Thinking2018** [ZYunH/zmail#78]
似乎get_mails()只能得到收件箱里的邮件，如何得到除了收件箱以外其他信箱里的邮件呢？
比如，希望得到 “草稿箱”或者自定义的文件夹里的邮件。

还有，似乎并不能得到所有的邮件，我收件箱里有158封邮件，可是server.stat()返回告诉我只有33封邮件

**Comment by ZYunH** [comment]
如果server.stat()的数目不正确，主要原因是邮箱设置的问题，一些邮箱会限制SMTP的邮件数量，你可以通过更改邮箱设置来改变这个情况。
