### ISSUE TITLE
使用抄送模式发送邮件，源码里面为什么要把抄送地址追加到收件地址？

### ISSUE THREAD

**Issue by bolianlai** [ZYunH/zmail#80]
在我使用抄送模式发送邮件的时候，使用了两层for循环，第一层例初始化了收件地址和抄送地址，第二层循环发送多封邮件，但是会在发送多封邮件的时候出现抄送地址追加到收件地址的情况，源码里这么写的目的是什么啊？

send_mail函数中的部分源码：
#Add Carbon Copy address.
cc = make_list(cc) if cc is not None else None
if cc is not None:
    for address in cc:
        recipients.append(address)
    _mail.set_mime_header('Cc', make_address_header(cc))

**Comment by ZYunH** [comment]
因为抄送这件事实际上是发送方自己做的 服务器并没有收到一封抄送邮件 然后帮你发送这样的逻辑
