### ISSUE TITLE
TypeError: Can not use ssl and tls together

### ISSUE THREAD

**Issue by ZuoGuocai** [ZYunH/zmail#81]
I  usually  send email via exchange servers like this :
```
def sendMail(body):
    url = 'my_smtpserver'
    conn = smtplib.SMTP(url,25)
    conn.starttls()
    user,password = ('username','password')
    conn.login(user,password)
```
but  I can't find   smtp tls  in your  documents.  Can  I  send  email  through  zmail  to use  tls support?

When I set  the key of zmail.server  like  smtp_tls=True,but neither not work  correctly. The error message in the below
```
 File "/usr/local/lib/python3.8/site-packages/zmail/abc.py", line 31, in __init__
    raise TypeError('Can not use ssl and tls together.')
TypeError: Can not use ssl and tls together.
```

**Comment by ZYunH** [comment]
Sure. But SMTP TLS can only be used alone, since you can't use ssl and tls together as the TypeError says. All you need to do is just disable SSL and enable TLS by `smtp_tls=True, smtp_ssl=False`.
In fact, TLS or SSL will enabled automatically, you don't need to care about this in most cases.

**Comment by ZuoGuocai** [comment]
I got it. As you said, I try to send email via zmail successfully. The detail config  in the below. Thanks for your reply.

```
 server = zmail.server('username', 'password', smtp_host='exchange-server-ip', smtp_port=25,smtp_tls=True, smtp_ssl=False)
```

**Comment by ZuoGuocai** [comment]
> Sure. But SMTP TLS can only be used alone, since you can't use ssl and tls together as the TypeError says. All you need to do is just disable SSL and enable TLS by `smtp_tls=True, smtp_ssl=False`.
> In fact, TLS or SSL will enabled automatically, you don't need to care about this in most cases.

I got it. As you said, I try to send email via zmail successfully. The detail config  in the below. Thanks for your reply.

```
 server = zmail.server('username', 'password', smtp_host='exchange-server-ip', smtp_port=25,smtp_tls=True, smtp_ssl=False)
```

**Comment by ZYunH** [comment]
In this case, looks like zmail use the default config, since it can't find the config in https://github.com/ZYunH/zmail/blob/master/zmail/info.py , i guess you use a private email server?
