### ISSUE TITLE
Tom邮箱无法使用

### ISSUE THREAD

**Issue by Lifestrive** [ZYunH/zmail#87]
[CRITICAL] POPServer access error :b'-ERR Invalid User Name'

邮箱mail.om.com

我使用poplib 测试了pop正常

希望解决

**Comment by Lifestrive** [comment]
mail.tom.com

**Comment by ZYunH** [comment]
这是因为这个邮箱不在配置里面，默认的配置对其也不生效，建议可以参考下邮箱服务器的具体配置来自定义参数使用。
