### ISSUE TITLE
删除邮件盲区，求解答

### ISSUE THREAD

**Issue by Lifestrive** [ZYunH/zmail#88]
MailServer.delete(which)
此处which是邮箱得序号吗？
那如果我通过server.get_mail查找邮件时候，得到邮箱内容，返回list, 但是无法知道ID
无法进行删除啊，还是通过其他函数去再寻找一次。

**Comment by Lifestrive** [comment]
server.get_mail是不是可以增加返回一个ID值？

**Comment by Lifestrive** [comment]
get_mails打错了

**Comment by ZYunH** [comment]
每封邮件都存在ID，存储在其中的items中
