### ISSUE TITLE
Hey,想问一下带条件的get_mail功能正常的响应时间是多少？

### ISSUE THREAD

**Issue by VinciMin** [ZYunH/zmail#91]
首先感谢你为我们造一个卓越的轮子。
我想请问一下，当我使用下方这个语句的时候，哪怕只有筛选1天的邮件，速度也会非常的慢。请问一下这个语句正常的响应时间是多少秒/分钟？
MailServer.get_mails(subject=None,start_time=None,end_time=None,sender=None,start_index=None,end_index=None)

**Comment by ZYunH** [comment]
因为get_mails实际是拿到了**所有邮件**的index信息(例如邮件名和发送时间等)，所以一般取决于邮件的总数，事实上这是个比较慢的API。

**Comment by VinciMin** [comment]
谢谢～
此外我还想问一下，如果附件名称为中文，是不是就无法解析了？我下载之后中文名称的文件将会被作为“Untitled”文件保存。

**Comment by ZYunH** [comment]
这个情况一般是出现解析问题，例如邮件格式不规范，或者解析程序问题。可以尝试使用一些较为简单的中文，不要携带复杂的编码。
