### ISSUE TITLE
似乎附件过大的时候发不出去？

### ISSUE THREAD

**Issue by choosingausernameisannoying** [ZYunH/zmail#93]
嘿，首先zmail很好用，真的十分感谢
但是发现发送比较大的zip（56.2MB）时的时候，会连接中断然后发送失败
报错先是
    return self._sslobj.write(data)
ConnectionAbortedError: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。
然后
    raise SMTPServerDisconnected('Server not connected')
smtplib.SMTPServerDisconnected: Server not connected
请问有什么解决办法吗？

**Comment by ZYunH** [comment]
这个问题目前没有很好的办法，一般是因为本地与邮件服务器之间的网络不稳定，或者服务器限流导致的，建议不成功可以重复尝试。

**Comment by choosingausernameisannoying** [comment]
好的谢谢！
