### ISSUE TITLE
在import zmail使用server时出现AttributeError: module 'zmail' has no attribute 'server'的错误

### ISSUE THREAD

**Issue by AdminWhaleFall** [ZYunH/zmail#97]
# 环境
- Windows10 Python3.7 X86
- pip安装的zmail
# 截图
![image](https://user-images.githubusercontent.com/63758849/91012242-58b3bf80-e618-11ea-96cf-db507c2b9b56.png)
# 备注
逛了一圈CSDN的评论区发现其他小伙伴都有类似的错误[https://blog.csdn.net/zyh1308130221/article/details/79291675](CSDN原贴)
> 是不是我们有什么地方**操作错误**了，烦请作者大大**抽空指导**一下，谢谢啦  ღ( ´･ᴗ･` )比心

**Comment by ZYunH** [comment]
不要使用zmail.py来作为文件名，会导致引用的冲突

**Comment by AdminWhaleFall** [comment]
好的 谢谢 ღ( ´･ᴗ･` )
